#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ' 🏗️  Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint
npm run check-lint ||
(
    echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.';
    false;
)

# Check tsconfig
npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above, add changes and try to commit again.'
    false;
)

npm run build ||
(
    echo '🤡😂❌🤡 Failed to build. 🤡😂❌🤡
            View the errors above to see why.'
    false;
)

echo "Success Commite"